### ISSUE TITLE
Kilka poprawek do „Profile"

### ISSUE THREAD

**Issue by 0wczar** [IgorSwatowski/React-Admin-Panel#1]
- [ ] 1. Active w Sidebar nie dziala. zobacz ze powinien wskazywac tam gdzie powinien sie znajdowac.

- [x] 2. Tu powinien byc „Tabs vertical”

- [x] 3. Brakuje sekcji progress z tekstem ponizej.

- [x] 4. Background nie jest bialy… 

- [ ] 5. brakuje „active” w tabs.

![2020-08-31_22-26-43](https://user-images.githubusercontent.com/2330394/91766058-3ef71700-ebda-11ea-9bd6-38350d3bdc32.png)

**Comment by IgorSwatowski** [comment]
Poprawione #2, #3, #4: Link: https://brave-pasteur-898917.netlify.app/profile

**Comment by IgorSwatowski** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/34008204/93350695-34bf5480-f839-11ea-9fea-fc0462b61d05.png)
![Bez tytułu2](https://user-images.githubusercontent.com/34008204/93350702-35f08180-f839-11ea-942c-f430c867166c.png)
![Bez tytułu3](https://user-images.githubusercontent.com/34008204/93350707-3721ae80-f839-11ea-9eee-184037405803.png)

**Comment by 0wczar** [comment]
Done. Przechodzimy do nowego repo...
