### ISSUE TITLE
Poprawki do „Billing > Card"

### ISSUE THREAD

**Issue by 0wczar** [IgorSwatowski/React-Admin-Panel#10]
![2020-09-17_10-47-33](https://user-images.githubusercontent.com/2330394/93448608-1490a380-f8d4-11ea-90a7-84ad80d7f5dd.png)

**Comment by IgorSwatowski** [comment]
Poprawione 
![Bez tytułu](https://user-images.githubusercontent.com/34008204/93455413-9b497e80-f8dc-11ea-828f-7106f64e6aee.png)
