### ISSUE TITLE
Poprawki do „Billing"

### ISSUE THREAD

**Issue by 0wczar** [IgorSwatowski/React-Admin-Panel#2]
- [ ] 1. brak „active” w sidebar oraz tabs.

- [x] 2. tu nie powinno byc podkreslenia w btn „Edit” oraz „Billing”

- [ ] 3. Link dla „Billing” powinien byc niebieski, i tylko on poiwinien byc klikalny jak powrot.

![2020-08-31_22-45-03](https://user-images.githubusercontent.com/2330394/91767192-0f490e80-ebdc-11ea-8abc-8e006c1e48ab.png)
![2020-08-31_22-46-24](https://user-images.githubusercontent.com/2330394/91767201-1243ff00-ebdc-11ea-9301-254d5ceefbb0.png)

**Comment by IgorSwatowski** [comment]
Poprawione #2. Link: https://brave-pasteur-898917.netlify.app/billings

**Comment by IgorSwatowski** [comment]
Poprawiony link. Teraz działa pod adresem: https://modest-colden-30a652.netlify.app/

**Comment by IgorSwatowski** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/34008204/93341858-e86f1700-f82e-11ea-8751-4b5c8fa3caaa.png)

**Comment by IgorSwatowski** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/34008204/93341964-0c325d00-f82f-11ea-9584-0411e0d234e2.png)

**Comment by 0wczar** [comment]
Nowe poprawki: 
![2020-09-17_11-13-12](https://user-images.githubusercontent.com/2330394/93451264-3e979500-f8d7-11ea-9e9e-138f4df32854.png)

**Comment by 0wczar** [comment]
I jak idzie @IgorSwatowski

**Comment by IgorSwatowski** [comment]
Wszystko poprawione.
![Bez tytułu](https://user-images.githubusercontent.com/34008204/93486389-6d783000-f904-11ea-8043-3f38b89d90e2.png)

**Comment by 0wczar** [comment]
W card z tabela wyglad nie ma paddingu po lewej i prawej - dokladnie o to mi chodzilo. 

Table small - sam rozkminiles brawo, i to jedt ok.

**Comment by 0wczar** [comment]
Done. Przechodzimy do nowego repo...
