### ISSUE TITLE
Content powinien byc wysrodkowany

### ISSUE THREAD

**Issue by 0wczar** [IgorSwatowski/React-Admin-Panel#3]
![2020-09-08_10-46-03](https://user-images.githubusercontent.com/2330394/92454257-98ee7280-f1c0-11ea-9d3d-fd45ea386677.png)

**Comment by IgorSwatowski** [comment]
Poprawione#3: Wycentrowanie komponentów Link: https://brave-pasteur-898917.netlify.app/
