### ISSUE TITLE
[ AVATAR + BREADCRUMB + PROGRESS ] Do redo without `<List...>’, '<div...>’ etc.

### ISSUE THREAD

**Issue by 0wczar** [IgorSwatowski/React-Admin-Panel#4]
https://github.com/IgorSwatowski/React-Admin-Panel/blob/cd999100481efa977cfec9cc470e2a1dec487e58/src/components/molecules/BillingCard.js#L77-L109

**Comment by 0wczar** [comment]
@IgorSwatowski Prośba: Jak coś zrobisz - komentujesz w Issues. 

To jest komentarz odnośnie tego commit: https://github.com/IgorSwatowski/React-Admin-Panel/commit/ef7d718b8c4e071c3d16b00c5cd62e05dfca69bf

Wciąż do poprawy:
 - ma powinno być żadnych `<div`
 - w tym kompnencie nie powinno być: `<ListItemText>`
 - dwie wizualne uwagi
![2020-09-12_09-23-53](https://user-images.githubusercontent.com/2330394/92990130-da8d5f00-f4d9-11ea-917c-85197d6b08fa.png)
:

**Comment by IgorSwatowski** [comment]
1. Divy zostały usunięte.
2. ListItemText usunięty
3. Wizualne uwagi poprawione.

Link: https://modest-colden-30a652.netlify.app/

**Comment by 0wczar** [comment]
Ok, kilka przemyslen: 
- „john doe”
jest czescia breadcrumb
- nie jestem pewien tych flexowych „orderow”, ale musze to sprawdzic. Raczej uzylbym „ml-auto” dla prawej strony z”progress”.

**Comment by 0wczar** [comment]
- Ml=-34 etc. Nigdy czegos takiego nie widzialem. Chyba wiem jak to dziala u Ciebie, ale na pewno jes to źle pod względem kodu i przyszłych responsive.

Sugeruje: 
- wszystkie m={} i p uzywac od 1 do 5.

**Comment by 0wczar** [comment]
@IgorSwatowski Właśnie zmieniłem „John Doe”  na „Tomasz Owczarczyk” - oto efekt:
![2020-09-12_22-27-50 (1)](https://user-images.githubusercontent.com/2330394/93004452-62f61900-f547-11ea-8120-93c7258104a9.gif)

**Comment by 0wczar** [comment]
@IgorSwatowski Moim zdaniem nie ma sensu tego męczyć - musimy wrócić do podstaw czyli:
 - Grid
 - Flexbox
 - Box jako div
 - Box jako span

**Comment by IgorSwatowski** [comment]
1. "John Doe" zmieniony z Typography i przeniesiony do BreadCrumbs.
2. Dodanie podstawowych już styles responsive. [Wcześniej była pusta biała strona, teraz już powinno się coś wyświetlać]
3. Użyłem mx="auto" dla LinearProgress i dla niektórych innych kolejnych
4. Przerobiłem kod trochę bardziej. Zapakowałem niektóre boxy w jednego boxa. Usunąłem <form>

**Comment by 0wczar** [comment]
Wygląda prawie dobrze - pozbądź się tego `ml-28` - i zrób tak żeby było dobrze. @IgorSwatowski

**Comment by IgorSwatowski** [comment]
Pozbyłem się minusowych ml. Teraz powinno być wszystko dobrze.

**Comment by IgorSwatowski** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/34008204/93338449-a47a1300-f82a-11ea-9f88-6c058edc4219.png)

**Comment by 0wczar** [comment]
Done. Zamykam.
